version: "3.9"

services:
  # kafka cluster
  kafka-1:
    image: confluentinc/cp-kafka:7.5.2
    ports:
      - 9000:9000
      - 9010:9010
    environment:
      KAFKA_NODE_ID: 1
      # JVM configs
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
      # JMX configs
      KAFKA_JMX_PORT: 9010
      KAFKA_JMX_HOSTNAME: localhost
      # KRaft configs
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29001,2@kafka-2:29001,3@kafka-3:29001"
      # broker configs
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:29000,PLAINTEXT_HOST://kafka-1:9000"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-1:29000,CONTROLLER://kafka-1:29001,PLAINTEXT_HOST://0.0.0.0:9000"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      # cluster configs
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    healthcheck:
      test: ["CMD", "sh", "/bin/kafka-topics", "--bootstrap-server", "localhost:9000", "--list"]
      interval: 5s
      timeout: 10s
      retries: 3
  kafka-2:
    image: confluentinc/cp-kafka:7.5.2
    ports:
      - 9001:9001
      - 9011:9011
    environment:
      KAFKA_NODE_ID: 2
      # JVM configs
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
      # JMX configs
      KAFKA_JMX_PORT: 9011
      KAFKA_JMX_HOSTNAME: localhost
      # KRaft configs
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29001,2@kafka-2:29001,3@kafka-3:29001"
      # broker configs
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:29000,PLAINTEXT_HOST://kafka-2:9001"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-2:29000,CONTROLLER://kafka-2:29001,PLAINTEXT_HOST://0.0.0.0:9001"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      # cluster configs
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    healthcheck:
      test: ["CMD", "sh", "/bin/kafka-topics", "--bootstrap-server", "localhost:9001", "--list"]
      interval: 5s
      timeout: 10s
      retries: 3
  kafka-3:
    image: confluentinc/cp-kafka:7.5.2
    ports:
      - 9002:9002
      - 9012:9012
    environment:
      KAFKA_NODE_ID: 3
      # JVM configs
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
      # JMX configs
      KAFKA_JMX_PORT: 9012
      KAFKA_JMX_HOSTNAME: localhost
      # KRaft configs
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29001,2@kafka-2:29001,3@kafka-3:29001"
      # broker configs
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-3:29000,PLAINTEXT_HOST://kafka-3:9002"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-3:29000,CONTROLLER://kafka-3:29001,PLAINTEXT_HOST://0.0.0.0:9002"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      # cluster configs
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    healthcheck:
      test: ["CMD", "sh", "/bin/kafka-topics", "--bootstrap-server", "localhost:9002", "--list"]
      interval: 5s
      timeout: 10s
      retries: 3

  # rest proxy
  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.5.2
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - 8101:8101
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka-1:29000,kafka-2:29000,kafka-3:29000
      KAFKA_REST_LISTENERS: http://0.0.0.0:8101

  # kafka ui
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "dc1-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-1:29000,kafka-2:29000,kafka-3:29000"

networks:
  default:
    name: kafka-network
    external: true